### ISSUE TITLE
Question: Isolated Declarations

### ISSUE THREAD

**Issue by aminpaks** [microsoft/ts-fix#32]
Hi folks,

I'm trying to use `ts-fix` with the TS v5.5 but it's not reporting any errors related to `isolatedDeclarations`.
Would you clarify if `ts-fix` is working with these errors? 

<img width="484" alt="image" src="https://github.com/microsoft/ts-fix/assets/9244395/f5ead25f-8e48-4f45-bd87-1061faed2579">

<img width="866" alt="image" src="https://github.com/microsoft/ts-fix/assets/9244395/339ba7bd-f8aa-487f-bfcc-a18c6350eacc">

**Comment by jakebailey** [comment]
See #30

**Comment by aminpaks** [comment]
@jakebailey is there a trick I don't know, even with the commits from that branch I don't get any fixes! 🤷

**Comment by aminpaks** [comment]
[Here](https://github.com/aminpaks/isolated-declarations-test) is a minimal repo to reproduce the issue.

**Comment by aminpaks** [comment]
The issue is we need to pass individual tsconfig paths to `ts-fix` or it wouldn't work. This is confusing, and I believe most folks using composite projects will face this issue.

**Comment by jakebailey** [comment]
That sounds like a distinct issue to this one, right? As it should affect any and all fixes?
