### ISSUE TITLE
Build script fails if TypeScript is not globally available

### ISSUE THREAD

**Issue by bennycode** [microsoft/ts-fix#37]
Running `npm run build` (as described in the README) will fail if `tsc` is not available globally. Since "typescript" is not listed in the dependencies, it would be helpful to either add it or mention in the README that TypeScript needs to be installed globally.

**Comment by jakebailey** [comment]
I'm not sure what you mean; it's a listed dependency and running it will work from scripts. This is how pretty much everyone invokes tsc. E.g. https://github.com/jakebailey/hereby/blob/main/package.json#L80

**Comment by bennycode** [comment]
I was executing `npm run build` and got a `tsc: not found` error message. I thought I needed to install TypeScript globally, but since it's already listed in the dependencies, a simple `npm install` resolves the issue. I recommend adding this to the README, and I have submitted a PR to do so: https://github.com/microsoft/ts-fix/pull/38

**Comment by jakebailey** [comment]
Merged, thanks.

**Comment by bennycode** [comment]
Thank you 🙏 I am planning to make a video tutorial about "ts-fix". Will it be published on npm as a ready-to-use package, or is clone & compile the way to go?

**Comment by jakebailey** [comment]
This isn't really an officially supported tool; it has a number of known bugs. #29 tracks publishing it, but I would say that you can only clone and use it for now. There's a number changes that would need to be made before then (though they aren't written down).
